2019-07-25 19:49:08,509 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
2019-07-25 19:49:16,470 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/core/run.py", line 199, in load_agent_on_start
    _interpreter = NaturalLanguageInterpreter.create(nlu_model, endpoints.nlu)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/core/interpreter.py", line 53, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/core/interpreter.py", line 247, in __init__
    self._load_interpreter()
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/core/interpreter.py", line 267, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/model.py", line 301, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/model.py", line 328, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/components.py", line 433, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/registry.py", line 181, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 143, in load
    nlp = cls.load_model(model_name)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 47, in load_model
    return spacy.load(spacy_model_name, disable=["parser"])
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 129, in load_model_from_link
    return cls.load(**overrides)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/language.py", line 647, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/language.py", line 635, in <lambda>
    self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self))),
  File "vocab.pyx", line 380, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 391, in spacy.vectors.Vectors.from_disk
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 507, in from_disk
    def from_disk(path, readers, exclude):
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/engineio/client.py", line 41, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt
2019-07-25 19:50:10,843 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
2019-07-26 10:44:33,362 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
2019-07-26 10:45:56,308 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/visualization.html'
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /visualization.html not found
2019-07-26 10:45:56,354 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/favicon.ico'
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /favicon.ico not found
2019-07-26 11:11:16,912 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
2019-07-26 11:13:34,597 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
2019-07-26 11:39:55,570 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/core/run.py", line 199, in load_agent_on_start
    _interpreter = NaturalLanguageInterpreter.create(nlu_model, endpoints.nlu)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/core/interpreter.py", line 53, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/core/interpreter.py", line 247, in __init__
    self._load_interpreter()
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/core/interpreter.py", line 267, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/model.py", line 301, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/model.py", line 328, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/components.py", line 433, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/registry.py", line 181, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 143, in load
    nlp = cls.load_model(model_name)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 47, in load_model
    return spacy.load(spacy_model_name, disable=["parser"])
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 129, in load_model_from_link
    return cls.load(**overrides)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/language.py", line 647, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/language.py", line 635, in <lambda>
    self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self))),
  File "vocab.pyx", line 380, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 391, in spacy.vectors.Vectors.from_disk
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 507, in from_disk
    def from_disk(path, readers, exclude):
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/engineio/client.py", line 41, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt
2019-07-26 14:59:06,579 [DEBUG]  CORS: Configuring CORS with resources: {'/*': {'origins': [''], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': None, 'supports_credentials': False, 'max_age': None, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': {'/*': {'origins': ''}}, 'intercept_exceptions': True, 'always_send': True}}
2019-07-26 14:59:06,580 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
2019-07-26 14:59:06,580 [INFO ]  Starting Rasa server on http://localhost:5005
2019-07-26 14:59:06,581 [INFO ]  Enabling coroutine debugging. Loop id 93936540794344.
2019-07-26 14:59:06,587 [DEBUG]  Extracted model to '/tmp/tmp89422g9s'.
2019-07-26 14:59:18,952 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-07-26 14:59:18,958 [DEBUG]  Connected to InMemoryTrackerStore.
2019-07-26 14:59:18,962 [DEBUG]  Extracted model to '/tmp/tmpc0a9tvrm'.
2019-07-26 14:59:18,963 [DEBUG]  Using yaml library: /home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/ruamel/yaml/__init__.py
2019-07-26 14:59:31,786 [DEBUG]  Created a new lock for conversation 'default'
2019-07-26 14:59:31,786 [DEBUG]  Creating a new tracker for id 'default'.
2019-07-26 14:59:31,793 [DEBUG]  Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.676171999742772}' and entities '[]'
2019-07-26 14:59:31,793 [DEBUG]  Logged UserUtterance - tracker now has 2 events
2019-07-26 14:59:31,958 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-07-26 14:59:31,958 [DEBUG]  Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
2019-07-26 14:59:31,958 [DEBUG]  There is a memorised next action '17'
2019-07-26 14:59:31,959 [DEBUG]  There is no active form
2019-07-26 14:59:31,959 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-07-26 14:59:31,959 [DEBUG]  Predicted next action 'utter_greet' with confidence 1.00.
2019-07-26 14:59:31,959 [DEBUG]  Action 'utter_greet' ended with events '['BotUttered(text: Hello! I am MI Bot, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-07-26 14:59:31,961 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-07-26 14:59:31,961 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-07-26 14:59:31,962 [DEBUG]  Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
2019-07-26 14:59:31,962 [DEBUG]  There is a memorised next action '14'
2019-07-26 14:59:31,962 [DEBUG]  There is no active form
2019-07-26 14:59:31,962 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-07-26 14:59:31,962 [DEBUG]  Predicted next action 'utter_bot_actions' with confidence 1.00.
2019-07-26 14:59:31,962 [DEBUG]  Action 'utter_bot_actions' ended with events '['BotUttered(text: I can help you place new orders and get device information and recommendations. What can I do for you?, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-07-26 14:59:31,964 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-07-26 14:59:31,964 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-07-26 14:59:31,964 [DEBUG]  Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}]
2019-07-26 14:59:31,965 [DEBUG]  There is a memorised next action '0'
2019-07-26 14:59:31,965 [DEBUG]  There is no active form
2019-07-26 14:59:31,965 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-07-26 14:59:31,965 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-07-26 14:59:31,965 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-07-26 14:59:31,965 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-07-26 14:59:38,949 [INFO ]  Killing Sanic server now.
2019-07-26 14:59:45,662 [INFO ]  Starting Rasa server on http://localhost:5005
2019-07-26 14:59:53,862 [INFO ]  Killing Sanic server now.
2019-07-26 14:59:53,862 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/run.py", line 199, in load_agent_on_start
    _interpreter = NaturalLanguageInterpreter.create(nlu_model, endpoints.nlu)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 53, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 250, in __init__
    self._load_interpreter()
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 270, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/model.py", line 301, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/model.py", line 328, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/components.py", line 433, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/registry.py", line 181, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 143, in load
    nlp = cls.load_model(model_name)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 47, in load_model
    return spacy.load(spacy_model_name, disable=["parser"])
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 132, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 149, in load_model_from_link
    return cls.load(**overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 193, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 176, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/language.py", line 811, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 633, in from_disk
    reader(path / key)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/language.py", line 800, in <lambda>
    deserializers["vocab"] = lambda p: self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self)
  File "vocab.pyx", line 453, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 431, in spacy.vectors.Vectors.from_disk
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 628, in from_disk
    def from_disk(path, readers, exclude):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/socketio/client.py", line 25, in signal_handler
    return original_signal_handler(sig, frame)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/engineio/client.py", line 41, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt
2019-07-26 15:00:09,832 [INFO ]  Starting Rasa server on http://localhost:5005
2019-07-26 15:00:22,212 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-07-26 15:02:06,061 [INFO ]  Killing Sanic server now.
2019-07-26 15:02:49,386 [INFO ]  Starting Rasa server on http://localhost:5005
2019-07-26 15:03:02,037 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-07-26 15:03:14,250 [INFO ]  Killing Sanic server now.
2019-07-26 15:03:21,446 [INFO ]  Starting Rasa server on http://localhost:5005
2019-07-26 15:03:34,456 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-07-26 15:03:52,199 [ERROR]  Failed to extract slot budget with action suggestions_form
2019-07-26 15:05:33,421 [ERROR]  Failed to extract slot budget with action suggestions_form
2019-07-26 15:06:26,418 [INFO ]  Killing Sanic server now.
2019-07-26 15:11:36,078 [INFO ]  Starting Rasa server on http://localhost:5005
2019-07-26 15:11:48,606 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-07-26 15:12:30,594 [ERROR]  Failed to extract slot user_name with action user_info_form
2019-07-26 15:12:37,293 [ERROR]  Failed to extract slot user_name with action user_info_form
2019-07-26 16:13:48,811 [INFO ]  Killing Sanic server now.
2019-07-26 16:51:22,379 [INFO ]  Starting Rasa server on http://localhost:5005
2019-07-26 16:51:36,031 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-07-26 16:52:00,170 [INFO ]  Killing Sanic server now.
2019-07-26 17:04:42,809 [INFO ]  Starting Rasa server on http://localhost:5005
2019-07-26 17:04:56,067 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-07-26 17:06:38,830 [INFO ]  Killing Sanic server now.
2019-07-26 17:15:31,122 [INFO ]  Starting Rasa server on http://localhost:5005
2019-07-26 17:15:44,473 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-07-26 17:16:21,810 [ERROR]  Failed to fill utterance template '{'text': 'Here is the device info for {devices_list}: ----------- '}'. Tried to replace 'devices_list' but could not find a value for it. There is no slot with this name nor did you pass the value explicitly when calling the template. Return template without filling the template. 
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/nlg/template.py", line 115, in _fill_template_text
    template["text"] = text.format(template_vars)
KeyError: 'devices_list'
2019-07-26 17:17:31,373 [INFO ]  Killing Sanic server now.
2019-07-26 17:18:02,538 [INFO ]  Starting Rasa server on http://localhost:5005
2019-07-26 17:18:15,041 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-07-26 17:19:05,300 [ERROR]  Failed to fill utterance template '{'text': 'Here is the device info for {devices_list}: ----------- '}'. Tried to replace 'devices_list' but could not find a value for it. There is no slot with this name nor did you pass the value explicitly when calling the template. Return template without filling the template. 
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/nlg/template.py", line 115, in _fill_template_text
    template["text"] = text.format(template_vars)
KeyError: 'devices_list'
2019-07-26 17:22:43,054 [INFO ]  Killing Sanic server now.
2019-07-26 17:23:01,414 [INFO ]  Starting Rasa server on http://localhost:5005
2019-07-26 17:23:14,124 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-07-26 17:28:06,689 [INFO ]  Killing Sanic server now.
2019-07-26 17:28:12,641 [DEBUG]  CORS: Configuring CORS with resources: {'/*': {'origins': [''], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': None, 'supports_credentials': False, 'max_age': None, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': {'/*': {'origins': ''}}, 'intercept_exceptions': True, 'always_send': True}}
2019-07-26 17:28:12,642 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
2019-07-26 17:28:12,642 [INFO ]  Starting Rasa server on http://localhost:5005
2019-07-26 17:28:12,643 [INFO ]  Enabling coroutine debugging. Loop id 94678717770056.
2019-07-26 17:28:12,651 [DEBUG]  Extracted model to '/tmp/tmpo10l6cbo'.
2019-07-26 17:28:25,326 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-07-26 17:28:25,332 [DEBUG]  Connected to InMemoryTrackerStore.
2019-07-26 17:28:25,337 [DEBUG]  Extracted model to '/tmp/tmpv545vjfn'.
2019-07-26 17:28:25,338 [DEBUG]  Using yaml library: /home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/ruamel/yaml/__init__.py
2019-07-26 17:30:28,647 [DEBUG]  Created a new lock for conversation 'default'
2019-07-26 17:30:28,647 [DEBUG]  Creating a new tracker for id 'default'.
2019-07-26 17:30:28,653 [DEBUG]  Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.6101091016572762}' and entities '[]'
2019-07-26 17:30:28,654 [DEBUG]  Logged UserUtterance - tracker now has 2 events
2019-07-26 17:30:28,818 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-07-26 17:30:28,818 [DEBUG]  Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
2019-07-26 17:30:28,818 [DEBUG]  There is a memorised next action '19'
2019-07-26 17:30:28,818 [DEBUG]  There is no active form
2019-07-26 17:30:28,818 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-07-26 17:30:28,818 [DEBUG]  Predicted next action 'utter_greet' with confidence 1.00.
2019-07-26 17:30:28,819 [DEBUG]  Action 'utter_greet' ended with events '['BotUttered(text: Hello! I am MI Bot, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-07-26 17:30:28,821 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-07-26 17:30:28,821 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-07-26 17:30:28,821 [DEBUG]  Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}]
2019-07-26 17:30:28,821 [DEBUG]  There is a memorised next action '15'
2019-07-26 17:30:28,822 [DEBUG]  There is no active form
2019-07-26 17:30:28,822 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-07-26 17:30:28,822 [DEBUG]  Predicted next action 'utter_bot_actions' with confidence 1.00.
2019-07-26 17:30:28,822 [DEBUG]  Action 'utter_bot_actions' ended with events '['BotUttered(text: I can help you place new orders and get device information and recommendations. What can I do for you?, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-07-26 17:30:28,824 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-07-26 17:30:28,824 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-07-26 17:30:28,824 [DEBUG]  Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}]
2019-07-26 17:30:28,824 [DEBUG]  There is a memorised next action '0'
2019-07-26 17:30:28,825 [DEBUG]  There is no active form
2019-07-26 17:30:28,825 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-07-26 17:30:28,825 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-07-26 17:30:28,825 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-07-26 17:30:28,825 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-07-26 17:30:35,729 [DEBUG]  Created a new lock for conversation 'default'
2019-07-26 17:30:35,729 [DEBUG]  Recreating tracker for id 'default'
2019-07-26 17:30:35,737 [DEBUG]  Received user message 'i want more info' with intent '{'name': 'more_info', 'confidence': 0.4784116851480702}' and entities '[]'
2019-07-26 17:30:35,738 [DEBUG]  Logged UserUtterance - tracker now has 8 events
2019-07-26 17:30:35,742 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-07-26 17:30:35,743 [DEBUG]  Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'intent_more_info': 1.0, 'prev_action_listen': 1.0}]
2019-07-26 17:30:35,743 [DEBUG]  There is no memorised next action
2019-07-26 17:30:35,743 [DEBUG]  There is no active form
2019-07-26 17:30:35,744 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-07-26 17:30:35,744 [DEBUG]  Predicted next action 'utter_ask_device_info_name' with confidence 0.62.
2019-07-26 17:30:35,744 [DEBUG]  Action 'utter_ask_device_info_name' ended with events '['BotUttered(text: Please enter the exact name of the device you need information about:, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-07-26 17:30:35,748 [DEBUG]  There is no mapped action for the predicted intent, 'more_info'.
2019-07-26 17:30:35,748 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-07-26 17:30:35,749 [DEBUG]  Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'intent_more_info': 1.0, 'prev_action_listen': 1.0}, {'intent_more_info': 1.0, 'prev_utter_ask_device_info_name': 1.0}]
2019-07-26 17:30:35,749 [DEBUG]  There is no memorised next action
2019-07-26 17:30:35,749 [DEBUG]  There is no active form
2019-07-26 17:30:35,749 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-07-26 17:30:35,750 [DEBUG]  Predicted next action 'action_listen' with confidence 0.91.
2019-07-26 17:30:35,750 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-07-26 17:30:35,750 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-07-26 17:30:48,432 [DEBUG]  Created a new lock for conversation 'default'
2019-07-26 17:30:48,432 [DEBUG]  Recreating tracker for id 'default'
2019-07-26 17:30:48,440 [DEBUG]  Received user message 'device name is xiaomi redmi 7a' with intent '{'name': 'device_name', 'confidence': 0.38556966093117206}' and entities '[{'start': 15, 'end': 30, 'value': 'xiaomi redmi 7a', 'entity': 'devices_list', 'confidence': 0.9733942989177673, 'extractor': 'CRFEntityExtractor'}]'
2019-07-26 17:30:48,440 [DEBUG]  Current slot values: 
	budget: None
	camera: None
	device_name: None
	devices_list: xiaomi redmi 7a
	email_id: None
	requested_slot: None
	user_name: None
2019-07-26 17:30:48,440 [DEBUG]  Logged UserUtterance - tracker now has 13 events
2019-07-26 17:30:48,444 [DEBUG]  NLU confidence 0.38556966093117206 is lower than NLU threshold 0.40. 
2019-07-26 17:30:48,445 [DEBUG]  Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'intent_more_info': 1.0, 'prev_action_listen': 1.0}, {'intent_more_info': 1.0, 'prev_utter_ask_device_info_name': 1.0}, {'prev_action_listen': 1.0, 'intent_device_name': 1.0, 'entity_devices_list': 1.0}]
2019-07-26 17:30:48,445 [DEBUG]  There is no memorised next action
2019-07-26 17:30:48,445 [DEBUG]  There is no active form
2019-07-26 17:30:48,446 [DEBUG]  Predicted next action using policy_2_FallbackPolicy
2019-07-26 17:30:48,446 [DEBUG]  Predicted next action 'action_default_fallback' with confidence 1.00.
2019-07-26 17:30:48,446 [DEBUG]  Action 'action_default_fallback' ended with events '['BotUttered(text: I\'m sorry. I did not understand., data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})', 'UserUtteranceReverted()']'
2019-07-26 17:30:48,446 [DEBUG]  Current slot values: 
	budget: None
	camera: None
	device_name: None
	devices_list: None
	email_id: None
	requested_slot: None
	user_name: None
2019-07-26 17:30:48,451 [DEBUG]  There is no mapped action for the predicted intent, 'more_info'.
2019-07-26 17:30:48,451 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-07-26 17:30:48,451 [DEBUG]  Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'intent_more_info': 1.0, 'prev_action_listen': 1.0}, {'intent_more_info': 1.0, 'prev_utter_ask_device_info_name': 1.0}]
2019-07-26 17:30:48,451 [DEBUG]  There is no memorised next action
2019-07-26 17:30:48,452 [DEBUG]  There is no active form
2019-07-26 17:30:48,452 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-07-26 17:30:48,452 [DEBUG]  Predicted next action 'action_listen' with confidence 0.91.
2019-07-26 17:30:48,452 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-07-26 17:30:48,452 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-07-26 19:04:35,686 [INFO ]  Killing Sanic server now.
2019-07-29 12:28:01,054 [INFO ]  Starting Rasa server on http://localhost:5005
2019-07-29 12:28:14,718 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-07-30 11:13:43,013 [INFO ]  Killing Sanic server now.
2019-08-01 12:56:26,824 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 12:56:40,172 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 12:56:51,906 [ERROR]  Failed to run custom action 'suggestions_form'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: Cannot connect to host localhost:5055 ssl:None [Connection refused]
2019-08-01 12:56:51,906 [ERROR]  Encountered an exception while running action 'suggestions_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2019-08-01 12:56:58,455 [INFO ]  Killing Sanic server now.
2019-08-01 12:57:28,578 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 12:57:37,725 [INFO ]  Killing Sanic server now.
2019-08-01 12:57:37,725 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/run.py", line 199, in load_agent_on_start
    _interpreter = NaturalLanguageInterpreter.create(nlu_model, endpoints.nlu)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 53, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 250, in __init__
    self._load_interpreter()
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 270, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/model.py", line 301, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/model.py", line 328, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/components.py", line 433, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/registry.py", line 181, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 143, in load
    nlp = cls.load_model(model_name)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 47, in load_model
    return spacy.load(spacy_model_name, disable=["parser"])
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 132, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 149, in load_model_from_link
    return cls.load(**overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 193, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 176, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/language.py", line 811, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 633, in from_disk
    reader(path / key)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/language.py", line 800, in <lambda>
    deserializers["vocab"] = lambda p: self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self)
  File "vocab.pyx", line 453, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 431, in spacy.vectors.Vectors.from_disk
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 628, in from_disk
    def from_disk(path, readers, exclude):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/socketio/client.py", line 25, in signal_handler
    return original_signal_handler(sig, frame)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/engineio/client.py", line 41, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt
2019-08-01 12:57:48,804 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 12:58:01,603 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 12:58:29,294 [INFO ]  Killing Sanic server now.
2019-08-01 15:34:19,552 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 15:34:32,220 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 15:35:39,468 [ERROR]  Failed to extract slot device_name with action user_info_form
2019-08-01 15:35:49,481 [ERROR]  Failed to extract slot device_name with action user_info_form
2019-08-01 15:36:25,995 [ERROR]  Failed to extract slot device_name with action user_info_form
2019-08-01 15:36:31,470 [INFO ]  Killing Sanic server now.
2019-08-01 15:40:34,186 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 15:40:47,202 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 15:41:37,120 [INFO ]  Killing Sanic server now.
2019-08-01 15:42:26,084 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 15:42:38,794 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 15:48:36,014 [INFO ]  Killing Sanic server now.
2019-08-01 15:48:45,932 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 15:48:58,467 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 16:01:32,681 [INFO ]  Killing Sanic server now.
2019-08-01 16:02:17,875 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 16:02:30,569 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 16:02:42,141 [ERROR]  Failed to run custom action 'suggestions_form'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: Cannot connect to host localhost:5055 ssl:None [Connection refused]
2019-08-01 16:02:42,141 [ERROR]  Encountered an exception while running action 'suggestions_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2019-08-01 16:02:48,303 [INFO ]  Killing Sanic server now.
2019-08-01 16:02:59,244 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 16:03:11,930 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 16:04:22,501 [INFO ]  Killing Sanic server now.
2019-08-01 16:04:36,525 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 16:04:49,762 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 16:05:08,217 [ERROR]  Failed to extract slot camera with action suggestions_form
2019-08-01 16:05:11,475 [ERROR]  Failed to extract slot camera with action suggestions_form
2019-08-01 16:05:20,691 [INFO ]  Killing Sanic server now.
2019-08-01 16:18:51,944 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 16:19:04,455 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 16:20:46,988 [INFO ]  Killing Sanic server now.
2019-08-01 17:23:57,361 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 17:24:10,004 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 17:29:45,829 [ERROR]  Failed to run custom action 'suggestions_form'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: Cannot connect to host localhost:5055 ssl:None [Connection refused]
2019-08-01 17:29:45,830 [ERROR]  Encountered an exception while running action 'suggestions_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2019-08-01 17:29:50,510 [INFO ]  Killing Sanic server now.
2019-08-01 17:33:02,609 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 17:33:15,355 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 17:34:04,196 [ERROR]  Failed to extract slot user_name with action user_info_form
2019-08-01 17:49:36,103 [INFO ]  Killing Sanic server now.
2019-08-01 17:53:22,251 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 17:53:35,006 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 17:54:08,555 [INFO ]  Killing Sanic server now.
2019-08-01 17:54:28,029 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 17:54:40,992 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 17:54:56,732 [ERROR]  Failed to extract slot user_name with action user_info_form
2019-08-01 17:55:01,970 [INFO ]  Killing Sanic server now.
2019-08-01 17:55:09,051 [DEBUG]  CORS: Configuring CORS with resources: {'/*': {'origins': [''], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': None, 'supports_credentials': False, 'max_age': None, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': {'/*': {'origins': ''}}, 'intercept_exceptions': True, 'always_send': True}}
2019-08-01 17:55:09,052 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
2019-08-01 17:55:09,052 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 17:55:09,053 [INFO ]  Enabling coroutine debugging. Loop id 94580505603512.
2019-08-01 17:55:09,062 [DEBUG]  Extracted model to '/tmp/tmpvuw57r1f'.
2019-08-01 17:55:21,740 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 17:55:21,746 [DEBUG]  Connected to InMemoryTrackerStore.
2019-08-01 17:55:21,751 [DEBUG]  Extracted model to '/tmp/tmpawydj5ja'.
2019-08-01 17:55:21,753 [DEBUG]  Using yaml library: /home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/ruamel/yaml/__init__.py
2019-08-01 17:56:39,039 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:56:39,040 [DEBUG]  Creating a new tracker for id 'default'.
2019-08-01 17:56:39,047 [DEBUG]  Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.5741834763891883}' and entities '[]'
2019-08-01 17:56:39,048 [DEBUG]  Logged UserUtterance - tracker now has 2 events
2019-08-01 17:56:39,216 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:56:39,216 [DEBUG]  Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
2019-08-01 17:56:39,216 [DEBUG]  There is a memorised next action '19'
2019-08-01 17:56:39,216 [DEBUG]  There is no active form
2019-08-01 17:56:39,217 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 17:56:39,217 [DEBUG]  Predicted next action 'utter_greet' with confidence 1.00.
2019-08-01 17:56:39,217 [DEBUG]  Action 'utter_greet' ended with events '['BotUttered(text: Hello! I am MI Bot, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 17:56:39,219 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-08-01 17:56:39,219 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:56:39,219 [DEBUG]  Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}]
2019-08-01 17:56:39,220 [DEBUG]  There is a memorised next action '15'
2019-08-01 17:56:39,220 [DEBUG]  There is no active form
2019-08-01 17:56:39,220 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 17:56:39,220 [DEBUG]  Predicted next action 'utter_bot_actions' with confidence 1.00.
2019-08-01 17:56:39,220 [DEBUG]  Action 'utter_bot_actions' ended with events '['BotUttered(text: I can help you place new orders and get device information and recommendations. What can I do for you?, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 17:56:39,222 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-08-01 17:56:39,222 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:56:39,222 [DEBUG]  Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_bot_actions': 1.0}]
2019-08-01 17:56:39,223 [DEBUG]  There is a memorised next action '0'
2019-08-01 17:56:39,223 [DEBUG]  There is no active form
2019-08-01 17:56:39,223 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 17:56:39,223 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-08-01 17:56:39,223 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:56:39,223 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:56:43,819 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:56:43,819 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 17:56:43,826 [DEBUG]  Received user message 'buy new product' with intent '{'name': 'new_order', 'confidence': 0.6447536755029923}' and entities '[]'
2019-08-01 17:56:43,827 [DEBUG]  Logged UserUtterance - tracker now has 8 events
2019-08-01 17:56:43,831 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:56:43,832 [DEBUG]  Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_bot_actions': 1.0}, {'intent_new_order': 1.0, 'prev_action_listen': 1.0}]
2019-08-01 17:56:43,832 [DEBUG]  There is a memorised next action '21'
2019-08-01 17:56:43,832 [DEBUG]  There is no active form
2019-08-01 17:56:43,833 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 17:56:43,833 [DEBUG]  Predicted next action 'utter_has_user_decided' with confidence 1.00.
2019-08-01 17:56:43,833 [DEBUG]  Action 'utter_has_user_decided' ended with events '['BotUttered(text: Have you decided on a device to purchase?, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 17:56:43,837 [DEBUG]  There is no mapped action for the predicted intent, 'new_order'.
2019-08-01 17:56:43,837 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:56:43,837 [DEBUG]  Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_bot_actions': 1.0}, {'intent_new_order': 1.0, 'prev_action_listen': 1.0}, {'intent_new_order': 1.0, 'prev_utter_has_user_decided': 1.0}]
2019-08-01 17:56:43,837 [DEBUG]  There is a memorised next action '0'
2019-08-01 17:56:43,837 [DEBUG]  There is no active form
2019-08-01 17:56:43,838 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 17:56:43,838 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-08-01 17:56:43,838 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:56:43,838 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:56:45,647 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:56:45,647 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 17:56:45,653 [DEBUG]  Received user message 'yes' with intent '{'name': 'affirm', 'confidence': 0.6470573280967306}' and entities '[]'
2019-08-01 17:56:45,654 [DEBUG]  Logged UserUtterance - tracker now has 12 events
2019-08-01 17:56:45,657 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:56:45,657 [DEBUG]  Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_bot_actions': 1.0}, {'intent_new_order': 1.0, 'prev_action_listen': 1.0}, {'intent_new_order': 1.0, 'prev_utter_has_user_decided': 1.0}, {'intent_affirm': 1.0, 'prev_action_listen': 1.0}]
2019-08-01 17:56:45,658 [DEBUG]  There is a memorised next action '25'
2019-08-01 17:56:45,658 [DEBUG]  There is no active form
2019-08-01 17:56:45,658 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 17:56:45,658 [DEBUG]  Predicted next action 'user_info_form' with confidence 1.00.
2019-08-01 17:56:45,658 [DEBUG]  Calling action endpoint to run action 'user_info_form'.
2019-08-01 17:56:45,667 [DEBUG]  Action 'user_info_form' ended with events '['BotUttered(text: Please enter your name, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {"budget": null, "camera": null, "device_name": null, "devices_list": null, "email_id": null, "requested_slot": null, "user_name": null})', 'Form(user_info_form)', 'SlotSet(key: requested_slot, value: user_name)']'
2019-08-01 17:56:45,667 [DEBUG]  Current slot values: 
	budget: None
	camera: None
	device_name: None
	devices_list: None
	email_id: None
	requested_slot: user_name
	user_name: None
2019-08-01 17:56:45,670 [DEBUG]  There is no mapped action for the predicted intent, 'affirm'.
2019-08-01 17:56:45,670 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:56:45,671 [DEBUG]  Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_bot_actions': 1.0}, {'intent_new_order': 1.0, 'prev_action_listen': 1.0}, {'intent_new_order': 1.0, 'prev_utter_has_user_decided': 1.0}, {'intent_affirm': 1.0, 'prev_action_listen': 1.0}]
2019-08-01 17:56:45,671 [DEBUG]  There is a memorised next action '25'
2019-08-01 17:56:45,671 [DEBUG]  There is an active form 'user_info_form'
2019-08-01 17:56:45,671 [DEBUG]  Predicted next action using policy_4_FormPolicy
2019-08-01 17:56:45,671 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-08-01 17:56:45,671 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:56:45,672 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:56:50,809 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:56:50,809 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 17:56:50,817 [DEBUG]  Received user message 'divya n' with intent '{'name': 'user_info_inform', 'confidence': 0.583319535155816}' and entities '[]'
2019-08-01 17:56:50,817 [DEBUG]  Logged UserUtterance - tracker now has 18 events
2019-08-01 17:56:50,822 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:56:50,823 [DEBUG]  Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_bot_actions': 1.0}, {'intent_new_order': 1.0, 'prev_action_listen': 1.0}, {'intent_new_order': 1.0, 'prev_utter_has_user_decided': 1.0}, {'intent_affirm': 1.0, 'prev_action_listen': 1.0}]
2019-08-01 17:56:50,823 [DEBUG]  There is a memorised next action '25'
2019-08-01 17:56:50,823 [DEBUG]  There is an active form 'user_info_form'
2019-08-01 17:56:50,824 [DEBUG]  Predicted next action using policy_4_FormPolicy
2019-08-01 17:56:50,824 [DEBUG]  Predicted next action 'user_info_form' with confidence 1.00.
2019-08-01 17:56:50,824 [DEBUG]  Calling action endpoint to run action 'user_info_form'.
2019-08-01 17:56:50,829 [ERROR]  Failed to extract slot user_name with action user_info_form
2019-08-01 17:56:50,833 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:56:50,834 [DEBUG]  Current tracker state [{'intent_new_order': 1.0, 'prev_action_listen': 1.0}, {'intent_new_order': 1.0, 'prev_utter_has_user_decided': 1.0}, {'intent_affirm': 1.0, 'prev_action_listen': 1.0}, {'prev_user_info_form': 1.0, 'intent_affirm': 1.0, 'active_form_user_info_form': 1.0}, {'intent_user_info_inform': 1.0, 'prev_action_listen': 1.0, 'active_form_user_info_form': 1.0}]
2019-08-01 17:56:50,835 [DEBUG]  There is no memorised next action
2019-08-01 17:56:50,835 [DEBUG]  There is an active form 'user_info_form'
2019-08-01 17:56:50,836 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:56:50,836 [DEBUG]  Predicted next action 'action_deactivate_form' with confidence 0.74.
2019-08-01 17:56:50,837 [DEBUG]  Action 'action_deactivate_form' ended with events '['Form(None)', 'SlotSet(key: requested_slot, value: None)']'
2019-08-01 17:56:50,837 [DEBUG]  Current slot values: 
	budget: None
	camera: None
	device_name: None
	devices_list: None
	email_id: None
	requested_slot: None
	user_name: None
2019-08-01 17:56:50,840 [DEBUG]  There is no mapped action for the predicted intent, 'user_info_inform'.
2019-08-01 17:56:50,841 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:56:50,842 [DEBUG]  Current tracker state [{'intent_new_order': 1.0, 'prev_utter_has_user_decided': 1.0}, {'intent_affirm': 1.0, 'prev_action_listen': 1.0}, {'prev_user_info_form': 1.0, 'intent_affirm': 1.0, 'active_form_user_info_form': 1.0}, {'intent_user_info_inform': 1.0, 'prev_action_listen': 1.0, 'active_form_user_info_form': 1.0}, {'prev_action_deactivate_form': 1.0, 'intent_user_info_inform': 1.0}]
2019-08-01 17:56:50,842 [DEBUG]  There is no memorised next action
2019-08-01 17:56:50,842 [DEBUG]  There is no active form
2019-08-01 17:56:50,843 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:56:50,843 [DEBUG]  Predicted next action 'utter_goodbye' with confidence 0.69.
2019-08-01 17:56:50,843 [DEBUG]  Action 'utter_goodbye' ended with events '['BotUttered(text: I hope I have helped you. Goodbye!, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 17:56:50,847 [DEBUG]  There is no mapped action for the predicted intent, 'user_info_inform'.
2019-08-01 17:56:50,847 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:56:50,848 [DEBUG]  Current tracker state [{'intent_affirm': 1.0, 'prev_action_listen': 1.0}, {'prev_user_info_form': 1.0, 'intent_affirm': 1.0, 'active_form_user_info_form': 1.0}, {'intent_user_info_inform': 1.0, 'prev_action_listen': 1.0, 'active_form_user_info_form': 1.0}, {'prev_action_deactivate_form': 1.0, 'intent_user_info_inform': 1.0}, {'intent_user_info_inform': 1.0, 'prev_utter_goodbye': 1.0}]
2019-08-01 17:56:50,848 [DEBUG]  There is no memorised next action
2019-08-01 17:56:50,848 [DEBUG]  There is no active form
2019-08-01 17:56:50,848 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:56:50,848 [DEBUG]  Predicted next action 'action_listen' with confidence 0.96.
2019-08-01 17:56:50,849 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:56:50,849 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:57:18,574 [INFO ]  Killing Sanic server now.
2019-08-01 17:57:53,847 [DEBUG]  CORS: Configuring CORS with resources: {'/*': {'origins': [''], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': None, 'supports_credentials': False, 'max_age': None, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': {'/*': {'origins': ''}}, 'intercept_exceptions': True, 'always_send': True}}
2019-08-01 17:57:53,848 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
2019-08-01 17:57:53,848 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 17:57:53,849 [INFO ]  Enabling coroutine debugging. Loop id 94861047135256.
2019-08-01 17:57:53,857 [DEBUG]  Extracted model to '/tmp/tmpulaoxetb'.
2019-08-01 17:58:06,501 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 17:58:06,508 [DEBUG]  Connected to InMemoryTrackerStore.
2019-08-01 17:58:06,513 [DEBUG]  Extracted model to '/tmp/tmpbae35mcr'.
2019-08-01 17:58:06,514 [DEBUG]  Using yaml library: /home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/ruamel/yaml/__init__.py
2019-08-01 17:58:15,811 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:58:15,811 [DEBUG]  Creating a new tracker for id 'default'.
2019-08-01 17:58:15,818 [DEBUG]  Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.5741834763891883}' and entities '[]'
2019-08-01 17:58:15,818 [DEBUG]  Logged UserUtterance - tracker now has 2 events
2019-08-01 17:58:15,992 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:15,992 [DEBUG]  Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
2019-08-01 17:58:15,992 [DEBUG]  There is a memorised next action '19'
2019-08-01 17:58:15,992 [DEBUG]  There is no active form
2019-08-01 17:58:15,992 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 17:58:15,993 [DEBUG]  Predicted next action 'utter_greet' with confidence 1.00.
2019-08-01 17:58:15,993 [DEBUG]  Action 'utter_greet' ended with events '['BotUttered(text: Hello! I am MI Bot, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 17:58:15,995 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-08-01 17:58:15,995 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:15,996 [DEBUG]  Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}]
2019-08-01 17:58:15,996 [DEBUG]  There is a memorised next action '15'
2019-08-01 17:58:15,996 [DEBUG]  There is no active form
2019-08-01 17:58:15,996 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 17:58:15,996 [DEBUG]  Predicted next action 'utter_bot_actions' with confidence 1.00.
2019-08-01 17:58:15,996 [DEBUG]  Action 'utter_bot_actions' ended with events '['BotUttered(text: I can help you place new orders and get device information and recommendations. What can I do for you?, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 17:58:15,998 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-08-01 17:58:15,998 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:15,999 [DEBUG]  Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}]
2019-08-01 17:58:15,999 [DEBUG]  There is a memorised next action '0'
2019-08-01 17:58:15,999 [DEBUG]  There is no active form
2019-08-01 17:58:15,999 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 17:58:15,999 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-08-01 17:58:15,999 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:58:15,999 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:58:22,331 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:58:22,332 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 17:58:22,340 [DEBUG]  Received user message 'buy new product' with intent '{'name': 'new_order', 'confidence': 0.6447536755029923}' and entities '[]'
2019-08-01 17:58:22,340 [DEBUG]  Logged UserUtterance - tracker now has 8 events
2019-08-01 17:58:22,345 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:22,345 [DEBUG]  Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_new_order': 1.0}]
2019-08-01 17:58:22,345 [DEBUG]  There is a memorised next action '21'
2019-08-01 17:58:22,346 [DEBUG]  There is no active form
2019-08-01 17:58:22,346 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 17:58:22,346 [DEBUG]  Predicted next action 'utter_has_user_decided' with confidence 1.00.
2019-08-01 17:58:22,346 [DEBUG]  Action 'utter_has_user_decided' ended with events '['BotUttered(text: Have you decided on a device to purchase?, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 17:58:22,350 [DEBUG]  There is no mapped action for the predicted intent, 'new_order'.
2019-08-01 17:58:22,350 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:22,350 [DEBUG]  Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_new_order': 1.0}, {'prev_utter_has_user_decided': 1.0, 'intent_new_order': 1.0}]
2019-08-01 17:58:22,350 [DEBUG]  There is a memorised next action '0'
2019-08-01 17:58:22,351 [DEBUG]  There is no active form
2019-08-01 17:58:22,351 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 17:58:22,351 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-08-01 17:58:22,351 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:58:22,351 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:58:24,340 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:58:24,341 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 17:58:24,353 [DEBUG]  Received user message 'yes' with intent '{'name': 'affirm', 'confidence': 0.6470573280967306}' and entities '[]'
2019-08-01 17:58:24,353 [DEBUG]  Logged UserUtterance - tracker now has 12 events
2019-08-01 17:58:24,358 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:24,359 [DEBUG]  Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_new_order': 1.0}, {'prev_utter_has_user_decided': 1.0, 'intent_new_order': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}]
2019-08-01 17:58:24,359 [DEBUG]  There is a memorised next action '25'
2019-08-01 17:58:24,359 [DEBUG]  There is no active form
2019-08-01 17:58:24,360 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 17:58:24,360 [DEBUG]  Predicted next action 'user_info_form' with confidence 1.00.
2019-08-01 17:58:24,360 [DEBUG]  Calling action endpoint to run action 'user_info_form'.
2019-08-01 17:58:24,369 [DEBUG]  Action 'user_info_form' ended with events '['BotUttered(text: Please enter your name, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {"budget": null, "camera": null, "device_name": null, "devices_list": null, "email_id": null, "requested_slot": null, "user_name": null})', 'Form(user_info_form)', 'SlotSet(key: requested_slot, value: user_name)']'
2019-08-01 17:58:24,369 [DEBUG]  Current slot values: 
	budget: None
	camera: None
	device_name: None
	devices_list: None
	email_id: None
	requested_slot: user_name
	user_name: None
2019-08-01 17:58:24,372 [DEBUG]  There is no mapped action for the predicted intent, 'affirm'.
2019-08-01 17:58:24,372 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:24,372 [DEBUG]  Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_new_order': 1.0}, {'prev_utter_has_user_decided': 1.0, 'intent_new_order': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}]
2019-08-01 17:58:24,373 [DEBUG]  There is a memorised next action '25'
2019-08-01 17:58:24,373 [DEBUG]  There is an active form 'user_info_form'
2019-08-01 17:58:24,373 [DEBUG]  Predicted next action using policy_4_FormPolicy
2019-08-01 17:58:24,373 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-08-01 17:58:24,373 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:58:24,374 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:58:30,559 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:58:30,559 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 17:58:30,567 [DEBUG]  Received user message 'tom cruise' with intent '{'name': 'user_info_inform', 'confidence': 0.21964238527092209}' and entities '[]'
2019-08-01 17:58:30,567 [DEBUG]  Logged UserUtterance - tracker now has 18 events
2019-08-01 17:58:30,572 [DEBUG]  NLU confidence 0.21964238527092209 is lower than NLU threshold 0.30. 
2019-08-01 17:58:30,573 [DEBUG]  Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_new_order': 1.0}, {'prev_utter_has_user_decided': 1.0, 'intent_new_order': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}]
2019-08-01 17:58:30,573 [DEBUG]  There is a memorised next action '25'
2019-08-01 17:58:30,573 [DEBUG]  There is an active form 'user_info_form'
2019-08-01 17:58:30,573 [DEBUG]  Predicted next action using policy_4_FormPolicy
2019-08-01 17:58:30,573 [DEBUG]  Predicted next action 'user_info_form' with confidence 1.00.
2019-08-01 17:58:30,574 [DEBUG]  Calling action endpoint to run action 'user_info_form'.
2019-08-01 17:58:30,580 [ERROR]  Failed to extract slot user_name with action user_info_form
2019-08-01 17:58:30,584 [DEBUG]  NLU confidence 0.21964238527092209 is lower than NLU threshold 0.30. 
2019-08-01 17:58:30,584 [DEBUG]  Current tracker state [{'prev_action_listen': 1.0, 'intent_new_order': 1.0}, {'prev_utter_has_user_decided': 1.0, 'intent_new_order': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_user_info_form': 1.0, 'active_form_user_info_form': 1.0, 'intent_affirm': 1.0}, {'active_form_user_info_form': 1.0, 'prev_action_listen': 1.0, 'intent_user_info_inform': 1.0}]
2019-08-01 17:58:30,585 [DEBUG]  There is no memorised next action
2019-08-01 17:58:30,585 [DEBUG]  There is an active form 'user_info_form'
2019-08-01 17:58:30,586 [DEBUG]  Predicted next action using policy_2_FallbackPolicy
2019-08-01 17:58:30,586 [DEBUG]  Predicted next action 'action_default_fallback' with confidence 1.00.
2019-08-01 17:58:30,586 [DEBUG]  Action 'action_default_fallback' ended with events '['BotUttered(text: I\'m sorry. I did not understand., data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})', 'UserUtteranceReverted()']'
2019-08-01 17:58:30,586 [DEBUG]  Current slot values: 
	budget: None
	camera: None
	device_name: None
	devices_list: None
	email_id: None
	requested_slot: user_name
	user_name: None
2019-08-01 17:58:30,590 [DEBUG]  There is no mapped action for the predicted intent, 'affirm'.
2019-08-01 17:58:30,590 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:30,591 [DEBUG]  Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_new_order': 1.0}, {'prev_utter_has_user_decided': 1.0, 'intent_new_order': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}]
2019-08-01 17:58:30,591 [DEBUG]  There is a memorised next action '25'
2019-08-01 17:58:30,591 [DEBUG]  There is an active form 'user_info_form'
2019-08-01 17:58:30,591 [DEBUG]  Predicted next action using policy_4_FormPolicy
2019-08-01 17:58:30,592 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-08-01 17:58:30,592 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:58:30,592 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:58:35,413 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:58:35,414 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 17:58:35,425 [DEBUG]  Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.5741834763891883}' and entities '[]'
2019-08-01 17:58:35,425 [DEBUG]  Logged UserUtterance - tracker now has 24 events
2019-08-01 17:58:35,430 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:35,432 [DEBUG]  Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_new_order': 1.0}, {'prev_utter_has_user_decided': 1.0, 'intent_new_order': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}]
2019-08-01 17:58:35,432 [DEBUG]  There is a memorised next action '25'
2019-08-01 17:58:35,432 [DEBUG]  There is an active form 'user_info_form'
2019-08-01 17:58:35,432 [DEBUG]  Predicted next action using policy_4_FormPolicy
2019-08-01 17:58:35,433 [DEBUG]  Predicted next action 'user_info_form' with confidence 1.00.
2019-08-01 17:58:35,433 [DEBUG]  Calling action endpoint to run action 'user_info_form'.
2019-08-01 17:58:35,439 [ERROR]  Failed to extract slot user_name with action user_info_form
2019-08-01 17:58:35,442 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:35,443 [DEBUG]  Current tracker state [{'prev_action_listen': 1.0, 'intent_new_order': 1.0}, {'prev_utter_has_user_decided': 1.0, 'intent_new_order': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_user_info_form': 1.0, 'active_form_user_info_form': 1.0, 'intent_affirm': 1.0}, {'active_form_user_info_form': 1.0, 'intent_greet': 1.0, 'prev_action_listen': 1.0}]
2019-08-01 17:58:35,443 [DEBUG]  There is no memorised next action
2019-08-01 17:58:35,443 [DEBUG]  There is an active form 'user_info_form'
2019-08-01 17:58:35,444 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:58:35,444 [DEBUG]  Predicted next action 'action_deactivate_form' with confidence 0.54.
2019-08-01 17:58:35,444 [DEBUG]  Action 'action_deactivate_form' ended with events '['Form(None)', 'SlotSet(key: requested_slot, value: None)']'
2019-08-01 17:58:35,444 [DEBUG]  Current slot values: 
	budget: None
	camera: None
	device_name: None
	devices_list: None
	email_id: None
	requested_slot: None
	user_name: None
2019-08-01 17:58:35,447 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-08-01 17:58:35,447 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:35,448 [DEBUG]  Current tracker state [{'prev_utter_has_user_decided': 1.0, 'intent_new_order': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_user_info_form': 1.0, 'active_form_user_info_form': 1.0, 'intent_affirm': 1.0}, {'active_form_user_info_form': 1.0, 'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_action_deactivate_form': 1.0}]
2019-08-01 17:58:35,448 [DEBUG]  There is no memorised next action
2019-08-01 17:58:35,448 [DEBUG]  There is no active form
2019-08-01 17:58:35,448 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:58:35,448 [DEBUG]  Predicted next action 'utter_goodbye' with confidence 0.41.
2019-08-01 17:58:35,449 [DEBUG]  Action 'utter_goodbye' ended with events '['BotUttered(text: I hope I have helped you. Goodbye!, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 17:58:35,452 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-08-01 17:58:35,452 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:35,452 [DEBUG]  Current tracker state [{'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_user_info_form': 1.0, 'active_form_user_info_form': 1.0, 'intent_affirm': 1.0}, {'active_form_user_info_form': 1.0, 'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_action_deactivate_form': 1.0}, {'intent_greet': 1.0, 'prev_utter_goodbye': 1.0}]
2019-08-01 17:58:35,453 [DEBUG]  There is no memorised next action
2019-08-01 17:58:35,453 [DEBUG]  There is no active form
2019-08-01 17:58:35,453 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:58:35,453 [DEBUG]  Predicted next action 'action_listen' with confidence 0.90.
2019-08-01 17:58:35,453 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:58:35,454 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:58:37,284 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:58:37,285 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 17:58:37,292 [DEBUG]  Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.5741834763891883}' and entities '[]'
2019-08-01 17:58:37,292 [DEBUG]  Logged UserUtterance - tracker now has 32 events
2019-08-01 17:58:37,299 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:37,300 [DEBUG]  Current tracker state [{'prev_user_info_form': 1.0, 'active_form_user_info_form': 1.0, 'intent_affirm': 1.0}, {'active_form_user_info_form': 1.0, 'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_action_deactivate_form': 1.0}, {'intent_greet': 1.0, 'prev_utter_goodbye': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
2019-08-01 17:58:37,301 [DEBUG]  There is no memorised next action
2019-08-01 17:58:37,301 [DEBUG]  There is no active form
2019-08-01 17:58:37,301 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:58:37,301 [DEBUG]  Predicted next action 'utter_greet' with confidence 0.81.
2019-08-01 17:58:37,301 [DEBUG]  Action 'utter_greet' ended with events '['BotUttered(text: Hello! I am MI Bot, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 17:58:37,305 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-08-01 17:58:37,305 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:37,306 [DEBUG]  Current tracker state [{'active_form_user_info_form': 1.0, 'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_action_deactivate_form': 1.0}, {'intent_greet': 1.0, 'prev_utter_goodbye': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}]
2019-08-01 17:58:37,306 [DEBUG]  There is no memorised next action
2019-08-01 17:58:37,306 [DEBUG]  There is no active form
2019-08-01 17:58:37,306 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:58:37,306 [DEBUG]  Predicted next action 'utter_bot_actions' with confidence 0.94.
2019-08-01 17:58:37,306 [DEBUG]  Action 'utter_bot_actions' ended with events '['BotUttered(text: I can help you place new orders and get device information and recommendations. What can I do for you?, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 17:58:37,310 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-08-01 17:58:37,310 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:37,311 [DEBUG]  Current tracker state [{'intent_greet': 1.0, 'prev_action_deactivate_form': 1.0}, {'intent_greet': 1.0, 'prev_utter_goodbye': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}]
2019-08-01 17:58:37,312 [DEBUG]  There is no memorised next action
2019-08-01 17:58:37,312 [DEBUG]  There is no active form
2019-08-01 17:58:37,312 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:58:37,312 [DEBUG]  Predicted next action 'action_listen' with confidence 0.94.
2019-08-01 17:58:37,312 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:58:37,313 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:58:44,316 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:58:44,317 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 17:58:44,329 [DEBUG]  Received user message 'get device info' with intent '{'name': 'more_info', 'confidence': 0.501306772447216}' and entities '[]'
2019-08-01 17:58:44,329 [DEBUG]  Logged UserUtterance - tracker now has 38 events
2019-08-01 17:58:44,334 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:44,335 [DEBUG]  Current tracker state [{'intent_greet': 1.0, 'prev_utter_goodbye': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_more_info': 1.0}]
2019-08-01 17:58:44,335 [DEBUG]  There is no memorised next action
2019-08-01 17:58:44,335 [DEBUG]  There is no active form
2019-08-01 17:58:44,335 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:58:44,336 [DEBUG]  Predicted next action 'utter_ask_device_info_name' with confidence 0.78.
2019-08-01 17:58:44,336 [DEBUG]  Action 'utter_ask_device_info_name' ended with events '['BotUttered(text: Please enter the exact name of the device you need information about:, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 17:58:44,339 [DEBUG]  There is no mapped action for the predicted intent, 'more_info'.
2019-08-01 17:58:44,340 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:44,341 [DEBUG]  Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_more_info': 1.0}, {'intent_more_info': 1.0, 'prev_utter_ask_device_info_name': 1.0}]
2019-08-01 17:58:44,341 [DEBUG]  There is no memorised next action
2019-08-01 17:58:44,341 [DEBUG]  There is no active form
2019-08-01 17:58:44,342 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:58:44,342 [DEBUG]  Predicted next action 'action_listen' with confidence 0.98.
2019-08-01 17:58:44,342 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:58:44,343 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:58:50,008 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:58:50,008 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 17:58:50,020 [DEBUG]  Received user message 'xiaomi redmi 7a' with intent '{'name': 'user_info_inform', 'confidence': 0.7190753397133847}' and entities '[{'start': 0, 'end': 15, 'value': 'xiaomi redmi 7a', 'entity': 'devices_list', 'confidence': 0.981928521610949, 'extractor': 'CRFEntityExtractor'}]'
2019-08-01 17:58:50,021 [DEBUG]  Current slot values: 
	budget: None
	camera: None
	device_name: None
	devices_list: xiaomi redmi 7a
	email_id: None
	requested_slot: None
	user_name: None
2019-08-01 17:58:50,021 [DEBUG]  Logged UserUtterance - tracker now has 43 events
2019-08-01 17:58:50,026 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:50,028 [DEBUG]  Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_more_info': 1.0}, {'intent_more_info': 1.0, 'prev_utter_ask_device_info_name': 1.0}, {'prev_action_listen': 1.0, 'intent_user_info_inform': 1.0, 'entity_devices_list': 1.0}]
2019-08-01 17:58:50,028 [DEBUG]  There is no memorised next action
2019-08-01 17:58:50,028 [DEBUG]  There is no active form
2019-08-01 17:58:50,029 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:58:50,029 [DEBUG]  Predicted next action 'utter_device_info' with confidence 0.82.
2019-08-01 17:58:50,029 [DEBUG]  Action 'utter_device_info' ended with events '['BotUttered(text: Here is the device info for xiaomi redmi 7a: ----------- , data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 17:58:50,033 [DEBUG]  There is no mapped action for the predicted intent, 'user_info_inform'.
2019-08-01 17:58:50,034 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:50,035 [DEBUG]  Current tracker state [{'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_more_info': 1.0}, {'intent_more_info': 1.0, 'prev_utter_ask_device_info_name': 1.0}, {'prev_action_listen': 1.0, 'intent_user_info_inform': 1.0, 'entity_devices_list': 1.0}, {'prev_utter_device_info': 1.0, 'intent_user_info_inform': 1.0, 'entity_devices_list': 1.0}]
2019-08-01 17:58:50,035 [DEBUG]  There is no memorised next action
2019-08-01 17:58:50,035 [DEBUG]  There is no active form
2019-08-01 17:58:50,035 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:58:50,035 [DEBUG]  Predicted next action 'action_listen' with confidence 0.95.
2019-08-01 17:58:50,035 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:58:50,036 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:58:53,982 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:58:53,983 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 17:58:53,999 [DEBUG]  Received user message 'ok' with intent '{'name': 'affirm', 'confidence': 0.6113529983307796}' and entities '[]'
2019-08-01 17:58:53,999 [DEBUG]  Logged UserUtterance - tracker now has 47 events
2019-08-01 17:58:54,007 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:54,009 [DEBUG]  Current tracker state [{'prev_action_listen': 1.0, 'intent_more_info': 1.0}, {'intent_more_info': 1.0, 'prev_utter_ask_device_info_name': 1.0}, {'prev_action_listen': 1.0, 'intent_user_info_inform': 1.0, 'entity_devices_list': 1.0}, {'prev_utter_device_info': 1.0, 'intent_user_info_inform': 1.0, 'entity_devices_list': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}]
2019-08-01 17:58:54,009 [DEBUG]  There is no memorised next action
2019-08-01 17:58:54,009 [DEBUG]  There is no active form
2019-08-01 17:58:54,009 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:58:54,009 [DEBUG]  Predicted next action 'utter_bot_actions' with confidence 0.56.
2019-08-01 17:58:54,010 [DEBUG]  Action 'utter_bot_actions' ended with events '['BotUttered(text: I can help you place new orders and get device information and recommendations. What can I do for you?, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 17:58:54,014 [DEBUG]  There is no mapped action for the predicted intent, 'affirm'.
2019-08-01 17:58:54,014 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:58:54,015 [DEBUG]  Current tracker state [{'intent_more_info': 1.0, 'prev_utter_ask_device_info_name': 1.0}, {'prev_action_listen': 1.0, 'intent_user_info_inform': 1.0, 'entity_devices_list': 1.0}, {'prev_utter_device_info': 1.0, 'intent_user_info_inform': 1.0, 'entity_devices_list': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_affirm': 1.0}]
2019-08-01 17:58:54,015 [DEBUG]  There is no memorised next action
2019-08-01 17:58:54,015 [DEBUG]  There is no active form
2019-08-01 17:58:54,015 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:58:54,015 [DEBUG]  Predicted next action 'action_listen' with confidence 0.95.
2019-08-01 17:58:54,016 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:58:54,017 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:59:04,772 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:59:04,772 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 17:59:04,780 [DEBUG]  Received user message 'get device recomendation' with intent '{'name': 'suggestion_intent', 'confidence': 0.3562640897346463}' and entities '[]'
2019-08-01 17:59:04,781 [DEBUG]  Logged UserUtterance - tracker now has 51 events
2019-08-01 17:59:04,786 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:59:04,787 [DEBUG]  Current tracker state [{'prev_action_listen': 1.0, 'intent_user_info_inform': 1.0, 'entity_devices_list': 1.0}, {'prev_utter_device_info': 1.0, 'intent_user_info_inform': 1.0, 'entity_devices_list': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_affirm': 1.0}, {'intent_suggestion_intent': 1.0, 'prev_action_listen': 1.0}]
2019-08-01 17:59:04,787 [DEBUG]  There is no memorised next action
2019-08-01 17:59:04,787 [DEBUG]  There is no active form
2019-08-01 17:59:04,787 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:59:04,787 [DEBUG]  Predicted next action 'utter_suggest' with confidence 0.81.
2019-08-01 17:59:04,788 [DEBUG]  Action 'utter_suggest' ended with events '['BotUttered(text: Sure! I can show you some suggestions., data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 17:59:04,791 [DEBUG]  There is no mapped action for the predicted intent, 'suggestion_intent'.
2019-08-01 17:59:04,792 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:59:04,793 [DEBUG]  Current tracker state [{'prev_utter_device_info': 1.0, 'intent_user_info_inform': 1.0, 'entity_devices_list': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_affirm': 1.0}, {'intent_suggestion_intent': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_suggest': 1.0, 'intent_suggestion_intent': 1.0}]
2019-08-01 17:59:04,793 [DEBUG]  There is no memorised next action
2019-08-01 17:59:04,793 [DEBUG]  There is no active form
2019-08-01 17:59:04,793 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:59:04,793 [DEBUG]  Predicted next action 'suggestions_form' with confidence 0.95.
2019-08-01 17:59:04,794 [DEBUG]  Calling action endpoint to run action 'suggestions_form'.
2019-08-01 17:59:04,802 [DEBUG]  Action 'suggestions_form' ended with events '['BotUttered(text: Please enter your estimated budget, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {"budget": null, "camera": null, "device_name": null, "devices_list": "xiaomi redmi 7a", "email_id": null, "requested_slot": null, "user_name": null})', 'Form(suggestions_form)', 'SlotSet(key: requested_slot, value: budget)']'
2019-08-01 17:59:04,802 [DEBUG]  Current slot values: 
	budget: None
	camera: None
	device_name: None
	devices_list: xiaomi redmi 7a
	email_id: None
	requested_slot: budget
	user_name: None
2019-08-01 17:59:04,805 [DEBUG]  There is no mapped action for the predicted intent, 'suggestion_intent'.
2019-08-01 17:59:04,805 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:59:04,806 [DEBUG]  Current tracker state [{'prev_utter_device_info': 1.0, 'intent_user_info_inform': 1.0, 'entity_devices_list': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_affirm': 1.0}, {'intent_suggestion_intent': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_suggest': 1.0, 'intent_suggestion_intent': 1.0}]
2019-08-01 17:59:04,806 [DEBUG]  There is no memorised next action
2019-08-01 17:59:04,806 [DEBUG]  There is an active form 'suggestions_form'
2019-08-01 17:59:04,806 [DEBUG]  Predicted next action using policy_4_FormPolicy
2019-08-01 17:59:04,806 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-08-01 17:59:04,807 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:59:04,808 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:59:12,134 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:59:12,135 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 17:59:12,142 [DEBUG]  Received user message 'budget is above 10k' with intent '{'name': 'suggestions_inform', 'confidence': 0.7687863274140389}' and entities '[{'start': 10, 'end': 19, 'value': 'above 10k', 'entity': 'budget', 'confidence': 0.901943324948201, 'extractor': 'CRFEntityExtractor'}]'
2019-08-01 17:59:12,142 [DEBUG]  Current slot values: 
	budget: above 10k
	camera: None
	device_name: None
	devices_list: xiaomi redmi 7a
	email_id: None
	requested_slot: budget
	user_name: None
2019-08-01 17:59:12,142 [DEBUG]  Logged UserUtterance - tracker now has 60 events
2019-08-01 17:59:12,147 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:59:12,148 [DEBUG]  Current tracker state [{'prev_utter_device_info': 1.0, 'intent_user_info_inform': 1.0, 'entity_devices_list': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_affirm': 1.0}, {'intent_suggestion_intent': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_suggest': 1.0, 'intent_suggestion_intent': 1.0}]
2019-08-01 17:59:12,149 [DEBUG]  There is no memorised next action
2019-08-01 17:59:12,149 [DEBUG]  There is an active form 'suggestions_form'
2019-08-01 17:59:12,149 [DEBUG]  Predicted next action using policy_4_FormPolicy
2019-08-01 17:59:12,149 [DEBUG]  Predicted next action 'suggestions_form' with confidence 1.00.
2019-08-01 17:59:12,149 [DEBUG]  Calling action endpoint to run action 'suggestions_form'.
2019-08-01 17:59:12,156 [DEBUG]  Action 'suggestions_form' ended with events '['BotUttered(text: Please enter camera specifications, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {"budget": "above 10k", "camera": null, "device_name": null, "devices_list": "xiaomi redmi 7a", "email_id": null, "requested_slot": "budget", "user_name": null})', 'SlotSet(key: budget, value: above 10k)', 'SlotSet(key: requested_slot, value: camera)']'
2019-08-01 17:59:12,156 [DEBUG]  Current slot values: 
	budget: above 10k
	camera: None
	device_name: None
	devices_list: xiaomi redmi 7a
	email_id: None
	requested_slot: camera
	user_name: None
2019-08-01 17:59:12,160 [DEBUG]  There is no mapped action for the predicted intent, 'suggestions_inform'.
2019-08-01 17:59:12,160 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:59:12,161 [DEBUG]  Current tracker state [{'prev_utter_device_info': 1.0, 'intent_user_info_inform': 1.0, 'entity_devices_list': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_affirm': 1.0}, {'intent_suggestion_intent': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_suggest': 1.0, 'intent_suggestion_intent': 1.0}]
2019-08-01 17:59:12,161 [DEBUG]  There is no memorised next action
2019-08-01 17:59:12,162 [DEBUG]  There is an active form 'suggestions_form'
2019-08-01 17:59:12,162 [DEBUG]  Predicted next action using policy_4_FormPolicy
2019-08-01 17:59:12,162 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-08-01 17:59:12,162 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:59:12,163 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:59:19,674 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:59:19,674 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 17:59:19,778 [DEBUG]  Received user message 'camera is below 5mp' with intent '{'name': 'suggestions_inform', 'confidence': 0.8353597544117222}' and entities '[{'start': 10, 'end': 19, 'value': 'below 5mp', 'entity': 'camera', 'confidence': 0.8268253093823141, 'extractor': 'CRFEntityExtractor'}]'
2019-08-01 17:59:19,778 [DEBUG]  Current slot values: 
	budget: above 10k
	camera: below 5mp
	device_name: None
	devices_list: xiaomi redmi 7a
	email_id: None
	requested_slot: camera
	user_name: None
2019-08-01 17:59:19,779 [DEBUG]  Logged UserUtterance - tracker now has 67 events
2019-08-01 17:59:19,785 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:59:19,787 [DEBUG]  Current tracker state [{'prev_utter_device_info': 1.0, 'intent_user_info_inform': 1.0, 'entity_devices_list': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_affirm': 1.0}, {'intent_suggestion_intent': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_suggest': 1.0, 'intent_suggestion_intent': 1.0}]
2019-08-01 17:59:19,787 [DEBUG]  There is no memorised next action
2019-08-01 17:59:19,787 [DEBUG]  There is an active form 'suggestions_form'
2019-08-01 17:59:19,787 [DEBUG]  Predicted next action using policy_4_FormPolicy
2019-08-01 17:59:19,788 [DEBUG]  Predicted next action 'suggestions_form' with confidence 1.00.
2019-08-01 17:59:19,788 [DEBUG]  Calling action endpoint to run action 'suggestions_form'.
2019-08-01 17:59:19,797 [DEBUG]  Action 'suggestions_form' ended with events '['BotUttered(text: Here are some recommendations for the specifications: budget: above 10k; camera: below 5mp , data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})', 'SlotSet(key: camera, value: below 5mp)', 'Form(None)', 'SlotSet(key: requested_slot, value: None)']'
2019-08-01 17:59:19,797 [DEBUG]  Current slot values: 
	budget: above 10k
	camera: below 5mp
	device_name: None
	devices_list: xiaomi redmi 7a
	email_id: None
	requested_slot: None
	user_name: None
2019-08-01 17:59:19,802 [DEBUG]  There is no mapped action for the predicted intent, 'suggestions_inform'.
2019-08-01 17:59:19,802 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:59:19,804 [DEBUG]  Current tracker state [{'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_affirm': 1.0}, {'intent_suggestion_intent': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_suggest': 1.0, 'intent_suggestion_intent': 1.0}, {'intent_suggestion_intent': 1.0, 'prev_suggestions_form': 1.0}]
2019-08-01 17:59:19,804 [DEBUG]  There is no memorised next action
2019-08-01 17:59:19,804 [DEBUG]  There is no active form
2019-08-01 17:59:19,804 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:59:19,805 [DEBUG]  Predicted next action 'action_listen' with confidence 0.92.
2019-08-01 17:59:19,805 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:59:19,806 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 17:59:42,398 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 17:59:42,398 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 17:59:42,406 [DEBUG]  Received user message 'ok' with intent '{'name': 'affirm', 'confidence': 0.6113529983307796}' and entities '[]'
2019-08-01 17:59:42,407 [DEBUG]  Logged UserUtterance - tracker now has 74 events
2019-08-01 17:59:42,415 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:59:42,417 [DEBUG]  Current tracker state [{'prev_utter_bot_actions': 1.0, 'intent_affirm': 1.0}, {'intent_suggestion_intent': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_suggest': 1.0, 'intent_suggestion_intent': 1.0}, {'intent_suggestion_intent': 1.0, 'prev_suggestions_form': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}]
2019-08-01 17:59:42,417 [DEBUG]  There is no memorised next action
2019-08-01 17:59:42,417 [DEBUG]  There is no active form
2019-08-01 17:59:42,417 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:59:42,417 [DEBUG]  Predicted next action 'action_deactivate_form' with confidence 0.48.
2019-08-01 17:59:42,417 [DEBUG]  Action 'action_deactivate_form' ended with events '['Form(None)', 'SlotSet(key: requested_slot, value: None)']'
2019-08-01 17:59:42,417 [DEBUG]  Current slot values: 
	budget: above 10k
	camera: below 5mp
	device_name: None
	devices_list: xiaomi redmi 7a
	email_id: None
	requested_slot: None
	user_name: None
2019-08-01 17:59:42,421 [DEBUG]  There is no mapped action for the predicted intent, 'affirm'.
2019-08-01 17:59:42,421 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 17:59:42,423 [DEBUG]  Current tracker state [{'intent_suggestion_intent': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_suggest': 1.0, 'intent_suggestion_intent': 1.0}, {'intent_suggestion_intent': 1.0, 'prev_suggestions_form': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'intent_affirm': 1.0, 'prev_action_deactivate_form': 1.0}]
2019-08-01 17:59:42,423 [DEBUG]  There is no memorised next action
2019-08-01 17:59:42,423 [DEBUG]  There is no active form
2019-08-01 17:59:42,423 [DEBUG]  Predicted next action using policy_0_KerasPolicy
2019-08-01 17:59:42,424 [DEBUG]  Predicted next action 'action_listen' with confidence 0.31.
2019-08-01 17:59:42,424 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 17:59:42,425 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 18:00:39,963 [INFO ]  Killing Sanic server now.
2019-08-01 18:01:22,498 [DEBUG]  CORS: Configuring CORS with resources: {'/*': {'origins': [''], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': None, 'supports_credentials': False, 'max_age': None, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': {'/*': {'origins': ''}}, 'intercept_exceptions': True, 'always_send': True}}
2019-08-01 18:01:22,498 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
2019-08-01 18:01:22,499 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 18:01:22,500 [INFO ]  Enabling coroutine debugging. Loop id 94521650247944.
2019-08-01 18:01:22,508 [DEBUG]  Extracted model to '/tmp/tmpu__6ha1f'.
2019-08-01 18:01:22,812 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/run.py", line 199, in load_agent_on_start
    _interpreter = NaturalLanguageInterpreter.create(nlu_model, endpoints.nlu)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 53, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 250, in __init__
    self._load_interpreter()
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 270, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/model.py", line 301, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/model.py", line 328, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/components.py", line 433, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/registry.py", line 181, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 143, in load
    nlp = cls.load_model(model_name)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 47, in load_model
    return spacy.load(spacy_model_name, disable=["parser"])
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 132, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 149, in load_model_from_link
    return cls.load(**overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 193, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 176, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/language.py", line 811, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 633, in from_disk
    reader(path / key)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/language.py", line 800, in <lambda>
    deserializers["vocab"] = lambda p: self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self)
  File "vocab.pyx", line 447, in spacy.vocab.Vocab.from_disk
  File "strings.pyx", line 232, in spacy.strings.StringStore.from_disk
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/srsly/_json_api.py", line 51, in read_json
    return ujson.load(f)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/socketio/client.py", line 25, in signal_handler
    return original_signal_handler(sig, frame)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/engineio/client.py", line 41, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt
2019-08-01 18:01:31,796 [DEBUG]  CORS: Configuring CORS with resources: {'/*': {'origins': [''], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': None, 'supports_credentials': False, 'max_age': None, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': {'/*': {'origins': ''}}, 'intercept_exceptions': True, 'always_send': True}}
2019-08-01 18:01:31,797 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
2019-08-01 18:01:31,797 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 18:01:31,798 [INFO ]  Enabling coroutine debugging. Loop id 94909552920600.
2019-08-01 18:01:31,805 [DEBUG]  Extracted model to '/tmp/tmpkzc4iv8t'.
2019-08-01 18:01:44,761 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 18:01:44,767 [DEBUG]  Connected to InMemoryTrackerStore.
2019-08-01 18:01:44,772 [DEBUG]  Extracted model to '/tmp/tmpaq87x160'.
2019-08-01 18:01:44,773 [DEBUG]  Using yaml library: /home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/ruamel/yaml/__init__.py
2019-08-01 18:04:45,990 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 18:04:45,991 [DEBUG]  Creating a new tracker for id 'default'.
2019-08-01 18:04:45,998 [DEBUG]  Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.649873080318789}' and entities '[]'
2019-08-01 18:04:45,999 [DEBUG]  Logged UserUtterance - tracker now has 2 events
2019-08-01 18:04:46,171 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 18:04:46,172 [DEBUG]  Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
2019-08-01 18:04:46,172 [DEBUG]  There is a memorised next action '19'
2019-08-01 18:04:46,172 [DEBUG]  There is no active form
2019-08-01 18:04:46,172 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 18:04:46,172 [DEBUG]  Predicted next action 'utter_greet' with confidence 1.00.
2019-08-01 18:04:46,173 [DEBUG]  Action 'utter_greet' ended with events '['BotUttered(text: Hello! I am MI Bot, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 18:04:46,175 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-08-01 18:04:46,175 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 18:04:46,175 [DEBUG]  Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}]
2019-08-01 18:04:46,175 [DEBUG]  There is a memorised next action '15'
2019-08-01 18:04:46,175 [DEBUG]  There is no active form
2019-08-01 18:04:46,175 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 18:04:46,176 [DEBUG]  Predicted next action 'utter_bot_actions' with confidence 1.00.
2019-08-01 18:04:46,176 [DEBUG]  Action 'utter_bot_actions' ended with events '['BotUttered(text: I can help you place new orders and get device information and recommendations. What can I do for you?, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 18:04:46,178 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-08-01 18:04:46,178 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 18:04:46,178 [DEBUG]  Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}]
2019-08-01 18:04:46,178 [DEBUG]  There is a memorised next action '0'
2019-08-01 18:04:46,178 [DEBUG]  There is no active form
2019-08-01 18:04:46,178 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 18:04:46,178 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-08-01 18:04:46,179 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 18:04:46,179 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 18:04:51,537 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 18:04:51,537 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 18:04:51,545 [DEBUG]  Received user message 'buy new product' with intent '{'name': 'new_order', 'confidence': 0.6775921174418853}' and entities '[]'
2019-08-01 18:04:51,545 [DEBUG]  Logged UserUtterance - tracker now has 8 events
2019-08-01 18:04:51,550 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 18:04:51,551 [DEBUG]  Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_new_order': 1.0}]
2019-08-01 18:04:51,551 [DEBUG]  There is a memorised next action '21'
2019-08-01 18:04:51,551 [DEBUG]  There is no active form
2019-08-01 18:04:51,551 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 18:04:51,551 [DEBUG]  Predicted next action 'utter_has_user_decided' with confidence 1.00.
2019-08-01 18:04:51,552 [DEBUG]  Action 'utter_has_user_decided' ended with events '['BotUttered(text: Have you decided on a device to purchase?, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-01 18:04:51,556 [DEBUG]  There is no mapped action for the predicted intent, 'new_order'.
2019-08-01 18:04:51,556 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 18:04:51,556 [DEBUG]  Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_new_order': 1.0}, {'prev_utter_has_user_decided': 1.0, 'intent_new_order': 1.0}]
2019-08-01 18:04:51,557 [DEBUG]  There is a memorised next action '0'
2019-08-01 18:04:51,557 [DEBUG]  There is no active form
2019-08-01 18:04:51,557 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 18:04:51,557 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-08-01 18:04:51,557 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 18:04:51,558 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 18:04:53,359 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 18:04:53,359 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 18:04:53,368 [DEBUG]  Received user message 'yes' with intent '{'name': 'affirm', 'confidence': 0.7487912546997016}' and entities '[]'
2019-08-01 18:04:53,368 [DEBUG]  Logged UserUtterance - tracker now has 12 events
2019-08-01 18:04:53,372 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 18:04:53,372 [DEBUG]  Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_new_order': 1.0}, {'prev_utter_has_user_decided': 1.0, 'intent_new_order': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}]
2019-08-01 18:04:53,372 [DEBUG]  There is a memorised next action '25'
2019-08-01 18:04:53,372 [DEBUG]  There is no active form
2019-08-01 18:04:53,372 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-01 18:04:53,373 [DEBUG]  Predicted next action 'user_info_form' with confidence 1.00.
2019-08-01 18:04:53,373 [DEBUG]  Calling action endpoint to run action 'user_info_form'.
2019-08-01 18:04:53,382 [DEBUG]  Action 'user_info_form' ended with events '['BotUttered(text: Please enter your name, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {"budget": null, "camera": null, "devices_list": null, "email_id": null, "requested_slot": null, "user_name": null})', 'Form(user_info_form)', 'SlotSet(key: requested_slot, value: user_name)']'
2019-08-01 18:04:53,382 [DEBUG]  Current slot values: 
	budget: None
	camera: None
	devices_list: None
	email_id: None
	requested_slot: user_name
	user_name: None
2019-08-01 18:04:53,385 [DEBUG]  There is no mapped action for the predicted intent, 'affirm'.
2019-08-01 18:04:53,386 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 18:04:53,386 [DEBUG]  Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_new_order': 1.0}, {'prev_utter_has_user_decided': 1.0, 'intent_new_order': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}]
2019-08-01 18:04:53,386 [DEBUG]  There is a memorised next action '25'
2019-08-01 18:04:53,387 [DEBUG]  There is an active form 'user_info_form'
2019-08-01 18:04:53,387 [DEBUG]  Predicted next action using policy_4_FormPolicy
2019-08-01 18:04:53,387 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-08-01 18:04:53,387 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 18:04:53,387 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 18:04:57,441 [DEBUG]  Created a new lock for conversation 'default'
2019-08-01 18:04:57,442 [DEBUG]  Recreating tracker for id 'default'
2019-08-01 18:04:57,451 [DEBUG]  Received user message 'tom cruise' with intent '{'name': 'user_info_inform', 'confidence': 0.22278494700786564}' and entities '[]'
2019-08-01 18:04:57,451 [DEBUG]  Logged UserUtterance - tracker now has 18 events
2019-08-01 18:04:57,455 [DEBUG]  NLU confidence 0.22278494700786564 is lower than NLU threshold 0.30. 
2019-08-01 18:04:57,456 [DEBUG]  Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_new_order': 1.0}, {'prev_utter_has_user_decided': 1.0, 'intent_new_order': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}]
2019-08-01 18:04:57,456 [DEBUG]  There is a memorised next action '25'
2019-08-01 18:04:57,456 [DEBUG]  There is an active form 'user_info_form'
2019-08-01 18:04:57,456 [DEBUG]  Predicted next action using policy_4_FormPolicy
2019-08-01 18:04:57,456 [DEBUG]  Predicted next action 'user_info_form' with confidence 1.00.
2019-08-01 18:04:57,457 [DEBUG]  Calling action endpoint to run action 'user_info_form'.
2019-08-01 18:04:57,463 [ERROR]  Failed to extract slot user_name with action user_info_form
2019-08-01 18:04:57,467 [DEBUG]  NLU confidence 0.22278494700786564 is lower than NLU threshold 0.30. 
2019-08-01 18:04:57,468 [DEBUG]  Current tracker state [{'prev_action_listen': 1.0, 'intent_new_order': 1.0}, {'prev_utter_has_user_decided': 1.0, 'intent_new_order': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}, {'prev_user_info_form': 1.0, 'active_form_user_info_form': 1.0, 'intent_affirm': 1.0}, {'intent_user_info_inform': 1.0, 'prev_action_listen': 1.0, 'active_form_user_info_form': 1.0}]
2019-08-01 18:04:57,468 [DEBUG]  There is no memorised next action
2019-08-01 18:04:57,468 [DEBUG]  There is an active form 'user_info_form'
2019-08-01 18:04:57,469 [DEBUG]  Predicted next action using policy_2_FallbackPolicy
2019-08-01 18:04:57,469 [DEBUG]  Predicted next action 'action_default_fallback' with confidence 1.00.
2019-08-01 18:04:57,469 [DEBUG]  Action 'action_default_fallback' ended with events '['BotUttered(text: I\'m sorry. I did not understand., data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})', 'UserUtteranceReverted()']'
2019-08-01 18:04:57,469 [DEBUG]  Current slot values: 
	budget: None
	camera: None
	devices_list: None
	email_id: None
	requested_slot: user_name
	user_name: None
2019-08-01 18:04:57,472 [DEBUG]  There is no mapped action for the predicted intent, 'affirm'.
2019-08-01 18:04:57,472 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-01 18:04:57,473 [DEBUG]  Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'prev_utter_bot_actions': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_new_order': 1.0}, {'prev_utter_has_user_decided': 1.0, 'intent_new_order': 1.0}, {'prev_action_listen': 1.0, 'intent_affirm': 1.0}]
2019-08-01 18:04:57,473 [DEBUG]  There is a memorised next action '25'
2019-08-01 18:04:57,473 [DEBUG]  There is an active form 'user_info_form'
2019-08-01 18:04:57,473 [DEBUG]  Predicted next action using policy_4_FormPolicy
2019-08-01 18:04:57,473 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-08-01 18:04:57,473 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-01 18:04:57,474 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-01 18:04:59,605 [INFO ]  Killing Sanic server now.
2019-08-01 18:47:03,850 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-01 18:47:16,384 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-01 19:19:29,453 [INFO ]  Killing Sanic server now.
2019-08-02 11:28:37,956 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-02 11:28:45,634 [INFO ]  Killing Sanic server now.
2019-08-02 11:28:45,634 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/run.py", line 199, in load_agent_on_start
    _interpreter = NaturalLanguageInterpreter.create(nlu_model, endpoints.nlu)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 53, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 250, in __init__
    self._load_interpreter()
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 270, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/model.py", line 301, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/model.py", line 328, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/components.py", line 433, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/registry.py", line 181, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 143, in load
    nlp = cls.load_model(model_name)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 47, in load_model
    return spacy.load(spacy_model_name, disable=["parser"])
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 132, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 149, in load_model_from_link
    return cls.load(**overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 193, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 176, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/language.py", line 811, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 633, in from_disk
    reader(path / key)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/language.py", line 800, in <lambda>
    deserializers["vocab"] = lambda p: self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self)
  File "vocab.pyx", line 449, in spacy.vocab.Vocab.from_disk
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/pathlib.py", line 900, in __truediv__
    def __truediv__(self, key):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/socketio/client.py", line 25, in signal_handler
    return original_signal_handler(sig, frame)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/engineio/client.py", line 41, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt
2019-08-02 11:28:48,847 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-02 11:29:01,906 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-02 11:31:04,123 [ERROR]  Failed to extract slot user_name with action user_info_form
2019-08-02 11:31:07,572 [INFO ]  Killing Sanic server now.
2019-08-02 11:52:36,565 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-02 11:52:49,913 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-02 11:54:06,960 [INFO ]  Killing Sanic server now.
2019-08-02 11:54:10,153 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-02 11:54:22,557 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-02 11:57:16,837 [INFO ]  Killing Sanic server now.
2019-08-02 12:03:41,430 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-02 12:03:53,927 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-02 12:05:59,633 [INFO ]  Killing Sanic server now.
2019-08-02 12:12:59,822 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-02 12:13:13,618 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-02 12:17:50,863 [INFO ]  Killing Sanic server now.
2019-08-02 12:17:50,869 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/visualization.html'
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /visualization.html not found
2019-08-02 12:18:34,374 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-02 12:18:47,599 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-02 12:19:59,223 [INFO ]  Killing Sanic server now.
2019-08-08 11:48:13,676 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
2019-08-08 11:48:23,834 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/core/run.py", line 199, in load_agent_on_start
    _interpreter = NaturalLanguageInterpreter.create(nlu_model, endpoints.nlu)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/core/interpreter.py", line 53, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/core/interpreter.py", line 247, in __init__
    self._load_interpreter()
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/core/interpreter.py", line 267, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/model.py", line 301, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/model.py", line 328, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/components.py", line 433, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/registry.py", line 181, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 143, in load
    nlp = cls.load_model(model_name)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 47, in load_model
    return spacy.load(spacy_model_name, disable=["parser"])
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/__init__.py", line 21, in load
    return util.load_model(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 112, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 129, in load_model_from_link
    return cls.load(**overrides)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 173, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 156, in load_model_from_path
    return nlp.from_disk(model_path)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/language.py", line 647, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/language.py", line 635, in <lambda>
    self.vocab.from_disk(p) and _fix_pretrained_vectors_name(self))),
  File "vocab.pyx", line 380, in spacy.vocab.Vocab.from_disk
  File "vectors.pyx", line 391, in spacy.vectors.Vectors.from_disk
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/spacy/util.py", line 511, in from_disk
    reader(path / key)
  File "vectors.pyx", line 369, in spacy.vectors.Vectors.from_disk.load_key2row
  File "vectors.pyx", line 370, in spacy.vectors.Vectors.from_disk.load_key2row
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/msgpack_numpy.py", line 175, in unpack
    return _unpack(stream, **kwargs)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/msgpack/__init__.py", line 58, in unpack
    return unpackb(data, **kwargs)
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/msgpack_numpy.py", line 184, in unpackb
    return _unpackb(packed, **kwargs)
  File "msgpack/_unpacker.pyx", line 200, in msgpack._unpacker.unpackb
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/msgpack_numpy.py", line 81, in decode
    dtype=np.dtype(descr))[0]
  File "/home/ggku5dell1163/anaconda3/lib/python3.7/site-packages/engineio/client.py", line 41, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt
2019-08-08 11:49:02,152 [DEBUG]  CORS: Configuring CORS with resources: {'/*': {'origins': [''], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': None, 'supports_credentials': False, 'max_age': None, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': {'/*': {'origins': ''}}, 'intercept_exceptions': True, 'always_send': True}}
2019-08-08 11:49:02,153 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
2019-08-08 11:49:02,153 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-08 11:49:02,154 [INFO ]  Enabling coroutine debugging. Loop id 94742890367432.
2019-08-08 11:49:02,163 [DEBUG]  Extracted model to '/tmp/tmpb1tk0lbr'.
2019-08-08 11:49:15,799 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-08 11:49:15,807 [DEBUG]  Connected to InMemoryTrackerStore.
2019-08-08 11:49:15,813 [DEBUG]  Extracted model to '/tmp/tmp_00raars'.
2019-08-08 11:49:15,815 [DEBUG]  Using yaml library: /home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/ruamel/yaml/__init__.py
2019-08-08 11:49:20,626 [DEBUG]  Created a new lock for conversation 'default'
2019-08-08 11:49:20,626 [DEBUG]  Creating a new tracker for id 'default'.
2019-08-08 11:49:20,635 [DEBUG]  Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.5476182477194809}' and entities '[]'
2019-08-08 11:49:20,635 [DEBUG]  Logged UserUtterance - tracker now has 2 events
2019-08-08 11:49:20,811 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-08 11:49:20,811 [DEBUG]  Current tracker state [None, None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
2019-08-08 11:49:20,812 [DEBUG]  There is a memorised next action '20'
2019-08-08 11:49:20,812 [DEBUG]  There is no active form
2019-08-08 11:49:20,812 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-08 11:49:20,812 [DEBUG]  Predicted next action 'utter_greet' with confidence 1.00.
2019-08-08 11:49:20,812 [DEBUG]  Action 'utter_greet' ended with events '['BotUttered(text: Hello! I am MI Bot, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-08 11:49:20,815 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-08-08 11:49:20,815 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-08 11:49:20,815 [DEBUG]  Current tracker state [None, None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}]
2019-08-08 11:49:20,815 [DEBUG]  There is a memorised next action '16'
2019-08-08 11:49:20,815 [DEBUG]  There is no active form
2019-08-08 11:49:20,815 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-08 11:49:20,815 [DEBUG]  Predicted next action 'utter_bot_actions' with confidence 1.00.
2019-08-08 11:49:20,816 [DEBUG]  Action 'utter_bot_actions' ended with events '['BotUttered(text: I can help you place new orders and get device information and recommendations. What can I do for you?, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-08 11:49:20,818 [DEBUG]  There is no mapped action for the predicted intent, 'greet'.
2019-08-08 11:49:20,818 [DEBUG]  NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-08 11:49:20,818 [DEBUG]  Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_bot_actions': 1.0}]
2019-08-08 11:49:20,818 [DEBUG]  There is a memorised next action '0'
2019-08-08 11:49:20,818 [DEBUG]  There is no active form
2019-08-08 11:49:20,818 [DEBUG]  Predicted next action using policy_3_MemoizationPolicy
2019-08-08 11:49:20,818 [DEBUG]  Predicted next action 'action_listen' with confidence 1.00.
2019-08-08 11:49:20,819 [DEBUG]  Action 'action_listen' ended with events '[]'
2019-08-08 11:49:20,819 [DEBUG]  Deleted lock for conversation 'default' (unused)
2019-08-08 11:50:14,744 [INFO ]  Killing Sanic server now.
2019-08-09 10:37:59,376 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-09 10:38:13,412 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-09 10:46:58,282 [INFO ]  Killing Sanic server now.
2019-08-09 10:50:56,464 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-09 10:50:56,511 [ERROR]  Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1445, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1438, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1347, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 487, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 404, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/run.py", line 199, in load_agent_on_start
    _interpreter = NaturalLanguageInterpreter.create(nlu_model, endpoints.nlu)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 53, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 250, in __init__
    self._load_interpreter()
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/core/interpreter.py", line 270, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/model.py", line 301, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/model.py", line 328, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/components.py", line 433, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/registry.py", line 181, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 143, in load
    nlp = cls.load_model(model_name)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/rasa/nlu/utils/spacy_utils.py", line 47, in load_model
    return spacy.load(spacy_model_name, disable=["parser"])
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 132, in load_model
    return load_model_from_link(name, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 149, in load_model_from_link
    return cls.load(**overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/data/en/__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 193, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 163, in load_model_from_path
    cls = get_lang_class(meta["lang"])
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/util.py", line 70, in get_lang_class
    module = importlib.import_module(".lang.%s" % lang, "spacy")
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/lang/en/__init__.py", line 10, in <module>
    from .lemmatizer import LEMMA_RULES, LEMMA_INDEX, LEMMA_EXC, LOOKUP
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/spacy/lang/en/lemmatizer/__init__.py", line 4, in <module>
    from .lookup import LOOKUP  # noqa: F401
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 857, in get_code
  File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/socketio/client.py", line 25, in signal_handler
    return original_signal_handler(sig, frame)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/engineio/client.py", line 41, in signal_handler
    return original_signal_handler(sig, frame)
KeyboardInterrupt
2019-08-09 10:58:35,205 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-09 10:58:47,829 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-09 10:59:07,577 [INFO ]  Killing Sanic server now.
2019-08-09 11:18:05,300 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-09 11:18:17,983 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-09 11:18:53,601 [INFO ]  Killing Sanic server now.
2019-08-09 11:49:17,585 [INFO ]  Starting Rasa server on http://localhost:5005
2019-08-09 11:49:30,108 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-08-09 11:49:43,943 [ERROR]  Failed to extract slot user_name with action user_info_form
2019-08-09 11:49:53,793 [INFO ]  Killing Sanic server now.
2019-11-06 18:39:53,807 [INFO ]  Starting Rasa server on http://localhost:5005
2019-11-06 18:40:07,993 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-11-07 11:14:56,824 [INFO ]  Killing Sanic server now.
2019-11-07 11:16:43,916 [INFO ]  Starting Rasa server on http://localhost:5005
2019-11-07 11:16:57,374 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-11-07 11:17:26,234 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/version'
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /version not found
2019-11-07 11:17:52,227 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/'
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
2019-11-07 11:18:05,256 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/'
Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
2019-11-07 11:52:42,681 [INFO ]  Starting Rasa server on http://localhost:5005
2019-11-07 11:52:56,014 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-11-07 11:53:02,159 [ERROR]  Unable to start server
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 1112, in uvloop.loop.Loop._create_server
  File "uvloop/handles/streamserver.pyx", line 58, in uvloop.loop.UVStreamServer.listen
  File "uvloop/handles/streamserver.pyx", line 95, in uvloop.loop.UVStreamServer._fatal_error
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ggku5dell1163/anaconda3/envs/botenv/lib/python3.7/site-packages/sanic/server.py", line 745, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1684, in create_server
  File "uvloop/loop.pyx", line 1116, in uvloop.loop.Loop._create_server
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5005): address already in use
2020-11-13 13:24:20,515 [INFO ]  Starting Rasa server on http://localhost:5005
2020-11-13 13:24:34,056 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-11-13 13:24:46,570 [ERROR]  Failed to run custom action 'suggestions_form'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: Cannot connect to host localhost:5055 ssl:None [Connection refused]
2020-11-13 13:24:46,571 [ERROR]  Encountered an exception while running action 'suggestions_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2020-11-13 14:04:49,028 [INFO ]  Killing Sanic server now.
2020-11-13 14:05:06,566 [INFO ]  Starting Rasa server on http://localhost:5005
2020-11-13 14:05:18,875 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-11-13 14:06:23,152 [ERROR]  Failed to run custom action 'user_info_form'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: Cannot connect to host localhost:5055 ssl:None [Connection refused]
2020-11-13 14:06:23,153 [ERROR]  Encountered an exception while running action 'user_info_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2020-11-13 14:07:37,469 [INFO ]  Killing Sanic server now.
2020-11-13 15:09:44,235 [INFO ]  Starting Rasa server on http://localhost:5005
2020-11-13 15:09:57,526 [INFO ]  Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-11-13 15:10:18,910 [ERROR]  Failed to extract slot user_name with action user_info_form
2020-11-13 15:10:59,306 [ERROR]  Failed to extract slot devices_list with action user_info_form
2020-11-13 15:12:14,844 [INFO ]  Killing Sanic server now.
